# .goreleaser.yml
project_name: libgitops

# This is a library so we don't have any build targets, but having goreleaser automatically
# generate release notes for us is nice.
build:
  skip: true

# This automatically closes any milestone named the same as the tag
milestones:
  - close: true